### PR TITLE
Commands planning

### PR DESCRIPTION
**Pull request by lsorell**
Added commands document for general idea of what I want to do in v1 of this project.

### CODE REVIEW

**Review by crscillitoe — APPROVED** [review]
Would a command to get the status of a given tournament code make sense?

i.e. "NOT PLAYED", "ROTM WIN", "GSM WIN", "IN PROGRESS".

**Comment by lsorell** [comment]
> Would a command to get the status of a given tournament code make sense?
> 
> i.e. "NOT PLAYED", "ROTM WIN", "GSM WIN", "IN PROGRESS".

I don't think so. I want the tournament admins to have as little to do as possible with putting in a command with a tournament code. One tournament code is generated per series (Bo3). The match is then found using a combination of the matchId and tournament code. I don't know how that would work. I also don't plan on storing teams (as of right now) so all it would do is say blue or red side win.

**Comment by crscillitoe** [comment]
How will the tournament admins view the result of a match then? Post-match history form?

**Comment by lsorell** [comment]
> How will the tournament admins view the result of a match then? Post-match history form?

That's the idea for now. I will be saving result data so if I decide to change it down the road that can be done.

**Comment by lsorell** [comment]
The scope I want this to cover for now is basically to replace the people that did stats. It might become more than that, but that was my original idea for the project. Once I get just the stats working it will be easier to add other parts.

**Pull request merged**
